---
title: "CombineAnnualData.rmd"
author: "https://github.com/jrkkv5/FIN6572Fall2020/blob/master/National%20Debt/importNationalDebt.Rmd"
date: "11/4/2020"
output:
  pdf_document: default
  html_document: default
---

``` {r annual_data_HPI}


HPI_raw$annual <- ifelse(HPI_raw$quarter=="4", "1",NA  )

HPI_annual <- na.omit(HPI_raw)
#Adds annual variable to HPI df.


```


``` {r CombineAnnualData}

unemp_scrubbed_annual$year <- as.integer(unemp_scrubbed_annual$year)
unemp_scrubbed_annual$quarter <- as.integer(unemp_scrubbed_annual$quarter)
#converts unemployment datatypes to integers for successful merge

HPI_Unemp_Combined_Annual <- full_join(unemp_scrubbed_annual, HPI_annual, by.x = "state", by.y = "year")
#combines HPI data with unemployment data

HPI_Unemp_Combined_Annual <- na.omit(HPI_Unemp_Combined_Annual)
#omits na entries for clean data

HPI_Unemp_MHI_Combined_Annual <- full_join(HPI_Unemp_Combined_Annual, MHI_raw, by.x = "state", by.y = "year")
#combines MHI data with unemployment data and HPI data

HPI_Unemp_MHI_Combined_Annual <- na.omit(HPI_Unemp_MHI_Combined_Annual)
#omits na entries for clean data

HPI_Unemp_MHI_poverty_Combined_Annual <- full_join(HPI_Unemp_MHI_Combined_Annual, poverty_raw, by.x = "state", by.y = "year")
#combines MHI data with unemployment data and HPI data

HPI_Unemp_MHI_poverty_Combined_Annual <- na.omit(HPI_Unemp_MHI_poverty_Combined_Annual)
#omits na entries for clean data



HPI_Population_Unemp_MHI_poverty_Combined_Annual <- full_join(HPI_Unemp_MHI_poverty_Combined_Annual, population, by.x = "state", by.y = "year")
#combines population data with unemployment data and HPI data

HPI_Population_Unemp_MHI_poverty_Combined_Annual <- na.omit(HPI_Population_Unemp_MHI_poverty_Combined_Annual)
#omits na entries for clean data

merged_final <- full_join(HPI_Population_Unemp_MHI_poverty_Combined_Annual, SP500, by.x = "state", by.y = "year")
#combines SP500 data with unemployment data and HPI data

merged_final <- na.omit(merged_final)
#omits na entries for clean data

```


