---
title: "Corey"
author: "https://github.com/jrkkv5/FIN6572Fall2020/blob/master/National%20Debt/importNationalDebt.Rmd"
date: "11/8/2020"
output: html_document
---
`````` {r ``` {r load_necessary_packages}
library(readr)
library(devtools)
library(blsAPI)
library(rjson)
library(curl)
library(dplyr)
library(tidyverse)
#Loads necessary packages

merged_final <- read_csv("csv files/mergedFinal.csv")
#Reads final file into merged dataframe

merged_final$log_pop = log(merged_final$population)

merged_final$log_RMHI = log(merged_final$RMHI)
```
``` {r CO Basic Analysis}

CO_observations <- merged_final[ merged_final$state == "CO", ]
CO_base <- CO_observations[ CO_observations$year < 2014, ] # Creates training set for model
CO_sampleset <-  CO_observations[ CO_observations$year > 2013, ] # Creates set to test model

scatter.smooth(CO_base$year, CO_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "blue")

scatter.smooth(CO_base$year, CO_base$HPI, main="HPI by Year", xlab = "Year", ylab = "HPI", col = "blue")

scatter.smooth(x=CO_base$year, y=CO_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "red")

scatter.smooth(x=CO_base$year, y=CO_base$poverty, main="% of People Below Poverty Level", xlab = "Year", ylab = "Poverty", ylim = c(0,20))

CO_base$RMHI <- as.integer(CO_base$RMHI)
plot(x=CO_base$year, y=CO_base$RMHI, main="Median Household Income by Year", xlab = "Year", ylab = "RMHI" )

CO_base$population <- as.integer(CO_base$population)
plot(x=CO_base$year, y=CO_base$population, main="Population by Year", xlab = "Year", ylab = "Population" )


cor(CO_base$RMHI, CO_base$value)
cor(CO_base$HPI, CO_base$value)
cor(CO_base$poverty, CO_base$value)
cor(CO_base$population, CO_base$value)
cor(CO_base$sp500, CO_base$value)
#run base correlations between categories and dependent variable

par(mfrow=c(1, 2))  # divide graph area in 2 columns
boxplot(CO_base$value, main="Unemployment", sub=paste("Outlier rows: ", boxplot.stats(CO_base$value)$out))  # box plot for 'Unemployment'
boxplot(CO_base$poverty, main="Poverty", sub=paste("Outlier rows: ", boxplot.stats(CO_base$poverty)$out))  # box plot for 'Poverty'
#create box plot for poverty level and unemployment level


CO_Test <- lm(value ~ poverty + RMHI + HPI + population + sp500, data = CO_base)
summary(CO_Test)
anova(CO_Test)
#run multiple linear model for data

CO_linearModelSignificant <- lm(value ~ poverty + population, data = CO_base)
summary(CO_linearModelSignificant)
#test to show a scatterplot CO HPI data against year

CO_linearModel <- lm(value ~ poverty + RMHI + HPI + log(population) + sp500, data = CO_base)
summary(CO_linearModel)
anova(CO_linearModel)
```
``` {r KS Basic Analysis}

KS_observations <- merged_final[ merged_final$state == "KS", ]
KS_base <- KS_observations[ KS_observations$year < 2014, ] # Creates training set for model
KS_sampleset <-  KS_observations[ KS_observations$year > 2013, ] # Creates set to test model

scatter.smooth(KS_base$year, KS_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "blue")

scatter.smooth(KS_base$year, KS_base$HPI, main="HPI by Year", xlab = "Year", ylab = "HPI", col = "blue")

scatter.smooth(x=KS_base$year, y=KS_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "red")

scatter.smooth(x=KS_base$year, y=KS_base$poverty, main="% of People Below Poverty Level", xlab = "Year", ylab = "Poverty", ylim = c(0,20))

KS_base$RMHI <- as.integer(KS_base$RMHI)
plot(x=KS_base$year, y=KS_base$RMHI, main="Median Household Income by Year", xlab = "Year", ylab = "RMHI" )

KS_base$population <- as.integer(KS_base$population)
plot(x=KS_base$year, y=KS_base$population, main="Population by Year", xlab = "Year", ylab = "Population" )


cor(KS_base$RMHI, KS_base$value)
cor(KS_base$HPI, KS_base$value)
cor(KS_base$poverty, KS_base$value)
cor(KS_base$population, KS_base$value)
cor(KS_base$sp500, KS_base$value)
#run base correlations between categories and dependent variable

par(mfrow=c(1, 2))  # divide graph area in 2 columns
boxplot(KS_base$value, main="Unemployment", sub=paste("Outlier rows: ", boxplot.stats(KS_base$value)$out))  # box plot for 'Unemployment'
boxplot(KS_base$poverty, main="Poverty", sub=paste("Outlier rows: ", boxplot.stats(KS_base$poverty)$out))  # box plot for 'Poverty'
#create box plot for poverty level and unemployment level


KS_Test <- lm(value ~ poverty + RMHI + HPI + population + sp500, data = KS_base)
summary(KS_Test)
anova(KS_Test)
#run multiple linear model for data

KS_linearModelSignificant <- lm(value ~ poverty + population, data = KS_base)
summary(KS_linearModelSignificant)
#test to show a scatterplot CA HPI data against year

KS_linearModel <- lm(value ~ poverty + RMHI + HPI + log(population) + sp500, data = KS_base)
summary(KS_linearModel)
anova(KS_linearModel)
```

``` {r CT Basic Analysis}

CT_observations <- merged_final[ merged_final$state == "CT", ]
CT_base <- CT_observations[ CT_observations$year < 2014, ] # Creates training set for model
CT_sampleset <-  CT_observations[ CT_observations$year > 2013, ] # Creates set to test model

scatter.smooth(CT_base$year, CT_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "blue")

scatter.smooth(CT_base$year, KS_base$HPI, main="HPI by Year", xlab = "Year", ylab = "HPI", col = "blue")

scatter.smooth(x=CT_base$year, y=CT_base$value, main="Unemployment by Year", xlab = "Year", ylab = "Unemployment", col = "red")

scatter.smooth(x=CT_base$year, y=CT_base$poverty, main="% of People Below Poverty Level", xlab = "Year", ylab = "Poverty", ylim = c(0,20))

CT_base$RMHI <- as.integer(CT_base$RMHI)
plot(x=CT_base$year, y=CT_base$RMHI, main="Median Household Income by Year", xlab = "Year", ylab = "RMHI" )

CT_base$population <- as.integer(CT_base$population)
plot(x=CT_base$year, y=CT_base$population, main="Population by Year", xlab = "Year", ylab = "Population" )


cor(CT_base$RMHI, CT_base$value)
cor(CT_base$HPI, CT_base$value)
cor(CT_base$poverty, CT_base$value)
cor(CT_base$population, CT_base$value)
cor(CT_base$sp500, CT_base$value)
#run base correlations between categories and dependent variable

par(mfrow=c(1, 2))  # divide graph area in 2 columns
boxplot(CT_base$value, main="Unemployment", sub=paste("Outlier rows: ", boxplot.stats(CT_base$value)$out))  # box plot for 'Unemployment'
boxplot(CT_base$poverty, main="Poverty", sub=paste("Outlier rows: ", boxplot.stats(CT_base$poverty)$out))  # box plot for 'Poverty'
#create box plot for poverty level and unemployment level


CT_Test <- lm(value ~ poverty + RMHI + HPI + population + sp500, data = CT_base)
summary(CT_Test)
anova(CT_Test)
#run multiple linear model for data

CT_linearModelSignificant <- lm(value ~ poverty + population, data = CT_base)
summary(CT_linearModelSignificant)
#test to show a scatterplot CA HPI data against year

CT_linearModel <- lm(value ~ poverty + RMHI + HPI + log(population) + sp500, data = CT_base)
summary(CT_linearModel)
anova(CT_linearModel)
```