---
title: "Unemployment Rates Via BLS API"
output: html_notebook
---

First, install the BLS API library, if needed.
```{r install_blsapi}
install.packages('blsAPI')
install.packages("curl")
install.packages('RCurl')
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyverse")
```

```{r packages}
library(devtools)
library(blsAPI)
library(rjson)
library(curl)
```

See example 2 at <https://github.com/mikeasilva/blsAPI> and adapt code.

Note: Create your own API key at <https://data.bls.gov/registrationEngine/> and insert the key they email you as the registration key parameter.

Pull the data via the API: 
```{r import}
unemp = data.frame()
startyear = 1948
endyear = 1957
nreq = ceiling((2020-1948)/10)
for (i in 1:nreq){
  if(endyear > 2020){
    endyear = 2020
  }
  payload <- list(
  'seriesid'=c('LAUST290000000000003'),
  'startyear'=startyear,
  'endyear'=endyear,
  'registrationkey'="01f3421bc9504301b5c0de6951908ef3")
  response <- blsAPI(payload, 2)
  json <- fromJSON(response)
  apiDF <- function(data){
    df <- data.frame(year=character(),
                     period=character(),
                     periodName=character(),
                     value=character(),
                     stringsAsFactors=FALSE)
    i <- 0
    for(d in data){
      i <- i + 1
      df[i,] <- unlist(d)
    }
    return(df)
  }
  unemppart <- apiDF(json$Results$series[[1]]$data)
  unemp_MO = rbind(unemp_MO,unemppart)
  startyear=startyear+10
  endyear=endyear+10
}
index <- with(unemp_MO, order(year, period))
unemp = unemp[index, ]
#https://www.bls.gov/help/hlpforma.htm#SM
```
