---
title: "Read_HPI.rmd"
author: "https://github.com/jrkkv5/FIN6572Fall2020/blob/master/National%20Debt/importNationalDebt.Rmd"
date: "10/31/2020"
output: html_document
---

```{r HPI}
HPI_raw <- read.csv("C:\\Users\\ABowles0608\\Desktop\\FIN6572Fall2020\\Project csv files\\HPI_AT_state.csv")
#Reads HPI into new dataframe

MHI_raw <- read.csv("C:\\Users\\ABowles0608\\Desktop\\FIN6572Fall2020\\Project csv files\\MHI.csv")
#Reads MHI into a new dataframe

poverty_raw <- read.csv("C:\\Users\\ABowles0608\\Desktop\\FIN6572Fall2020\\Project csv files\\povertylevel.csv")
#Reads Poverty level by state into new data frame

population <- read.csv("C:\\Users\\ABowles0608\\Desktop\\FIN6572Fall2020\\National Debt\\Unemployment_Project\\csv files\\population_by_year2.csv")
#source: https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html

```


```{r industry}


industry <- read.csv("C:\\Users\\nores\\OneDrive\\Desktop\\Fin 6572\\occupational numbers.csv")
#Reads 
#source: https://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-people.html

```


